apiVersion: v1
kind: Service
metadata:
  name: crypto-db-service
spec:
  ports:
    - port: 3306
      targetPort: 3306

  selector:
    name: crypto-db
    app: onboarding-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: crypto-db
      app: onboarding-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: crypto-db-pod
      labels:
        name: crypto-db
        app: onboarding-app
    spec:
      containers:
        - name: crypto-db
          image: mysql:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
          env:
            - name: MYSQL_DATABASE
              value: "cryptos"
            - name: MYSQL_PASSWORD
              value: "veljkosql"
            - name: MYSQL_ROOT_PASSWORD
              value: "veljkosql"
          imagePullPolicy: Never
          ports:
            - containerPort: 3306

