version: "3.7"
services:
  crypto-db:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cryptos
      MYSQL_USER: root
      MYSQL_PASSWORD: veljkosql
      MYSQL_ROOT_PASSWORD: veljkosql

  crypto-recommendation-service:
    image: crypto-recommendation-api:1.1.1
    ports:
      - "8080:8080"
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - crypto-db
    environment:
      MYSQL_USER: veljko
      MYSQL_PASSWORD: veljkosql
      DB_SERVER: crypto-db:3306
